
import java.awt.image.BufferedImage;
import java.io.ByteArrayOutputStream;
import java.io.File;
import java.io.FileInputStream;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.Statement;
import java.util.Date;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author kanis
 */
public class Principal extends javax.swing.JFrame {
    
    Connection con = null;
    Statement stmt = null;
    java.sql.ResultSet rs = null; //Import to Result Set


    /**
     * Creates new form Principal
     */
    public Principal() {
        initComponents();
        
         con = databaseConnection.connection();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        PRINCIPAL = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        imageIcon = new javax.swing.JLabel();
        SelectImage = new javax.swing.JButton();
        Pcontact = new javax.swing.JTextField();
        Pid = new javax.swing.JTextField();
        Paddress = new javax.swing.JTextField();
        Page = new javax.swing.JTextField();
        Pbirthday = new javax.swing.JTextField();
        Pgender = new javax.swing.JComboBox<>();
        Pname = new javax.swing.JTextField();
        AddPrincipal = new javax.swing.JButton();
        Ppastpresent = new javax.swing.JComboBox<>();
        SubmitPrincipal = new javax.swing.JButton();
        DeletePrincipal = new javax.swing.JButton();
        SearchPrincipal = new javax.swing.JButton();
        UpdatePrincipal1 = new javax.swing.JButton();
        mainManuBtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 51));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        PRINCIPAL.setFont(new java.awt.Font("Segoe UI", 1, 48)); // NOI18N
        PRINCIPAL.setForeground(new java.awt.Color(255, 0, 0));
        PRINCIPAL.setText("PRINCIPAL ");
        jPanel1.add(PRINCIPAL, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 20, -1, -1));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setText("ID");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 190, -1, -1));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setText("CONTACT NO.");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 660, -1, -1));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 0));
        jLabel3.setText("NAME");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 410, -1, -1));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 0, 0));
        jLabel4.setText("ADDRESS");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 460, -1, -1));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 0, 0));
        jLabel5.setText("AGE");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 510, -1, -1));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 0, 0));
        jLabel6.setText("BIRTHDAY");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 560, -1, -1));

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(0, 0, 0));
        jLabel7.setText("GENDER");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 610, -1, -1));

        imageIcon.setBorder(javax.swing.BorderFactory.createMatteBorder(3, 3, 3, 3, new java.awt.Color(0, 0, 0)));
        jPanel1.add(imageIcon, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 120, 210, 180));

        SelectImage.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        SelectImage.setText("SELECT IMAGE");
        SelectImage.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SelectImageActionPerformed(evt);
            }
        });
        jPanel1.add(SelectImage, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 320, -1, -1));

        Pcontact.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        Pcontact.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PcontactActionPerformed(evt);
            }
        });
        jPanel1.add(Pcontact, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 660, 360, -1));

        Pid.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        Pid.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PidActionPerformed(evt);
            }
        });
        jPanel1.add(Pid, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 190, 160, -1));

        Paddress.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        Paddress.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PaddressActionPerformed(evt);
            }
        });
        jPanel1.add(Paddress, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 460, 360, -1));

        Page.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        Page.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PageActionPerformed(evt);
            }
        });
        jPanel1.add(Page, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 510, 360, -1));

        Pbirthday.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        Pbirthday.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PbirthdayActionPerformed(evt);
            }
        });
        jPanel1.add(Pbirthday, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 560, 360, -1));

        Pgender.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        Pgender.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Choose Gender", "Male", "Female" }));
        jPanel1.add(Pgender, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 610, -1, -1));

        Pname.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        Pname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PnameActionPerformed(evt);
            }
        });
        jPanel1.add(Pname, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 410, 360, -1));

        AddPrincipal.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        AddPrincipal.setText("ADD");
        AddPrincipal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddPrincipalActionPerformed(evt);
            }
        });
        jPanel1.add(AddPrincipal, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 350, -1, -1));

        Ppastpresent.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        Ppastpresent.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "PAST", "PRESENT" }));
        jPanel1.add(Ppastpresent, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 290, -1, -1));

        SubmitPrincipal.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        SubmitPrincipal.setText("SUBMIT");
        SubmitPrincipal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SubmitPrincipalActionPerformed(evt);
            }
        });
        jPanel1.add(SubmitPrincipal, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 650, 140, 50));

        DeletePrincipal.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        DeletePrincipal.setText("DELETE");
        DeletePrincipal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DeletePrincipalActionPerformed(evt);
            }
        });
        jPanel1.add(DeletePrincipal, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 410, -1, -1));

        SearchPrincipal.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        SearchPrincipal.setText("SEARCH");
        SearchPrincipal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SearchPrincipalActionPerformed(evt);
            }
        });
        jPanel1.add(SearchPrincipal, new org.netbeans.lib.awtextra.AbsoluteConstraints(840, 190, -1, -1));

        UpdatePrincipal1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        UpdatePrincipal1.setText("UPDATE");
        UpdatePrincipal1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UpdatePrincipal1ActionPerformed(evt);
            }
        });
        jPanel1.add(UpdatePrincipal1, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 350, -1, -1));

        mainManuBtn.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        mainManuBtn.setText("MAIN MENU");
        mainManuBtn.setActionCommand("jButton21");
        mainManuBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mainManuBtnActionPerformed(evt);
            }
        });
        jPanel1.add(mainManuBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(910, 20, 160, 50));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 1115, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 788, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void PcontactActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PcontactActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_PcontactActionPerformed

    private void PidActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PidActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_PidActionPerformed

    private void PaddressActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PaddressActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_PaddressActionPerformed

    private void PageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PageActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_PageActionPerformed

    private void PbirthdayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PbirthdayActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_PbirthdayActionPerformed

    private void PnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PnameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_PnameActionPerformed

    private void SubmitPrincipalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SubmitPrincipalActionPerformed
        // TODO add your handling code here:
           try{
            stmt = con.createStatement();
            
            
            int sId = Integer.parseInt(Pid.getText());
            String sName = Pname.getText();
            String sAddress = Paddress.getText();
            int sAge = Integer.parseInt(Page.getText());
             String sBirthday = Pbirthday.getText();
            String sGender = (String) Pgender.getSelectedItem();
            int sContact = Integer.parseInt(Pcontact.getText());
            String sPastpresent = (String) Ppastpresent.getSelectedItem();
            
            String query = "INSERT INTO principal (id, name, address, age, birthday, gender, contact, image, pastpresent) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?)";
            
            PreparedStatement preparedStmt = con.prepareStatement(query);
            preparedStmt.setInt(1, sId);
            preparedStmt.setString(2, sName);
            preparedStmt.setString(3, sAddress);
            preparedStmt.setInt(4, sAge);
            preparedStmt.setString(5, sBirthday);
            preparedStmt.setString(6, sGender);
            preparedStmt.setInt(7, sContact);
            preparedStmt.setBytes(8, photo);
            preparedStmt.setString(9, sPastpresent );
            
            preparedStmt.execute();
            JOptionPane.showMessageDialog(null, "ADDED");
            
        }
        catch(Exception e)
        {
            System.out.println(e);
        }
           
           Reset();
        
    }//GEN-LAST:event_SubmitPrincipalActionPerformed

    private void SelectImageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SelectImageActionPerformed
        // TODO add your handling code here: 
        JFileChooser chooser = new JFileChooser();
        chooser.showOpenDialog(null);
        File file = chooser.getSelectedFile();
        imageIcon.setIcon(new ImageIcon(file.toString()));
        filename = file.getAbsolutePath();
        
        try
        {
            File image = new File(filename);
            FileInputStream fis = new FileInputStream(image);
            ByteArrayOutputStream bos = new ByteArrayOutputStream();
            byte [] buf = new byte [1024];
            
            for(int readnum; (readnum = fis.read(buf)) != -1;)
            {
                bos.write(buf, 0, readnum);
            }
            photo = bos.toByteArray();
        }
        catch(Exception e)
        {
            System.out.println(e);
        }
    }//GEN-LAST:event_SelectImageActionPerformed

    
    private void Reset() {   //Create Reset Function
    Pid.setText("");
    Pname.setText("");
    Paddress.setText("");
    Page.setText("");
    Pbirthday.setText("");
    Pgender.setSelectedItem(null); // Reset to default or initial value
    Pcontact.setText("");
    Ppastpresent.setSelectedItem(null); // Reset to default or initial value
    
     // Reset the image-related component (assuming imageIcon is a JLabel)
    imageIcon.setIcon(null);
    
    // Select the first item in the JComboBox after reset
    
    if (Pgender.getItemCount() > 0) {
        Pgender.setSelectedItem(Pgender.getItemAt(0));
    }
    
    if (Ppastpresent.getItemCount() > 0) {
        Ppastpresent.setSelectedItem(Ppastpresent.getItemAt(0));
    }
}
     
    private void AddPrincipalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddPrincipalActionPerformed
        // TODO add your handling code here:
         Reset();
    }//GEN-LAST:event_AddPrincipalActionPerformed

    private void SearchPrincipalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SearchPrincipalActionPerformed
        // TODO add your handling code here:
         
        try{
            
             stmt = con.createStatement();
            
            int sId = Integer.parseInt(Pid.getText());
            
            String query = "SELECT * FROM principal";
            
            rs = stmt.executeQuery(query);
            
            while(rs.next()){
                if(sId == rs.getInt("id")){
                    Pname.setText(rs.getString("name"));
                    Paddress.setText(rs.getString("address"));
                    Page.setText(String.format("%s", rs.getInt("age")));
                    Pbirthday.setText(String.format("%tD", rs.getDate("birthday")));
                    Pgender.setSelectedItem(rs.getString("gender"));
                    Pcontact.setText(String.format(0 +  "%s", rs.getInt("contact")));
                    Ppastpresent.setSelectedItem(rs.getString("gender"));
                    
                     //Image Search
                    BufferedImage image = ImageIO.read(rs.getBinaryStream("image"));
                    imageIcon.setIcon(new ImageIcon(image));
                    
                    Ppastpresent.setSelectedItem(rs.getString("pastpresent"));
                }
            }
            
        }
        catch(Exception e){
            System.out.println(e);
        }
    }//GEN-LAST:event_SearchPrincipalActionPerformed

    private void UpdatePrincipal1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UpdatePrincipal1ActionPerformed
        // TODO add your handling code here:
         try
        {
            
            
            stmt = con.createStatement();
            
            int sId = Integer.parseInt(Pid.getText());
            String sName = Pname.getText();
            String sAddress = Paddress.getText();
            int sAge = Integer.parseInt(Page.getText());
            long Birthday = Date.parse(Pbirthday.getText());
            java.sql.Date sBirthday = new java.sql.Date(Birthday);
            String sGender = (String) Pgender.getSelectedItem();
            int sContact = Integer.parseInt(Pcontact.getText());
            String  sPastpresent = (String)  Ppastpresent.getSelectedItem();
            
          String query = "UPDATE principal SET name = ?, address = ?, age = ?, birthday = ?, gender = ?, contact = ?, image = ?, pastpresent=? WHERE id = ?";
            
            PreparedStatement preparedStmt = con.prepareStatement(query);
            
            preparedStmt.setString(1, sName);
            preparedStmt.setString(2, sAddress);
            preparedStmt.setInt(3, sAge);
            preparedStmt.setDate(4, sBirthday);
            preparedStmt.setString(5, sGender);
            preparedStmt.setInt(6, sContact);
            preparedStmt.setBytes(7, photo);
            preparedStmt.setString(8, sPastpresent);
            preparedStmt.setInt(9, sId);
            
            preparedStmt.executeUpdate();
            JOptionPane.showMessageDialog(null, "Details Updated Successfully!");
        }
        catch(Exception e)
        {
            System.out.println(e);
        }
         
         Reset();
    }//GEN-LAST:event_UpdatePrincipal1ActionPerformed

    private void DeletePrincipalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DeletePrincipalActionPerformed
        // TODO add your handling code here:
          try{
            
            stmt = con.createStatement();
            
            int sId = Integer.parseInt(Pid.getText());
            
            String query = "DELETE FROM principal WHERE id ='"+sId+"' ";
            
            stmt.execute(query);
            
            Reset();
            JOptionPane.showMessageDialog(null, "DELETED DETAILS SUCCESSFULL!");
        }
        
        catch(Exception e){
            System.out.println(e);
        }
          
          Reset();
    }//GEN-LAST:event_DeletePrincipalActionPerformed

    private void mainManuBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mainManuBtnActionPerformed
        // TODO add your handling code here:
        setVisible(false);
        Home view = new Home();
        view.setVisible(true);
    }//GEN-LAST:event_mainManuBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Principal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AddPrincipal;
    private javax.swing.JButton DeletePrincipal;
    private javax.swing.JLabel PRINCIPAL;
    private javax.swing.JTextField Paddress;
    private javax.swing.JTextField Page;
    private javax.swing.JTextField Pbirthday;
    private javax.swing.JTextField Pcontact;
    private javax.swing.JComboBox<String> Pgender;
    private javax.swing.JTextField Pid;
    private javax.swing.JTextField Pname;
    private javax.swing.JComboBox<String> Ppastpresent;
    private javax.swing.JButton SearchPrincipal;
    private javax.swing.JButton SelectImage;
    private javax.swing.JButton SubmitPrincipal;
    private javax.swing.JButton UpdatePrincipal1;
    private javax.swing.JLabel imageIcon;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton mainManuBtn;
    // End of variables declaration//GEN-END:variables

    
        byte [] photo = null;
        String filename = null;
}
